import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useIsAuthenticated, useMsal } from "@azure/msal-react";
import dynamic from "next/dynamic";

const SignInButton = dynamic(() => import("../components/SignInButton"), {
  ssr: false,
});
const SignOutButton = dynamic(() => import("../components/SignOutButton"), {
  ssr: false,
});

const Home: NextPage = () => {
  const isAuthenticated = useIsAuthenticated();
  const [account] = useMsal().accounts;
  console.log(isAuthenticated);
  console.log(account);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          {isAuthenticated ? <SignOutButton /> : <SignInButton />}
        </Container>
      </main>
    </>
  );
};

export default Home;
